### ISSUE TITLE
Change 'create predictor' syntrax

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_sql#100]
We need improve current syntax:
```
CREATE PREDICTOR pred
FROM integration_name 
WITH ('select * FROM table') 
AS ds_name
PREDICT f1 as f1_alias, f2
ORDER BY f_order_1 ASC, f_order_2, f_order_3 DESC
GROUP BY f_group_1, f_group_2
WINDOW 100
HORIZON 7
USING '{"x": 1, "y": "a"}'
```
1. remove parenthesis around query to user's db: `WITH (select * FROM table) `
2. remove mandatory `AS ds_name`, since now user have not control under datasets
3. (?) remove parenthesis around json in `using`: `USING {"x": 1, "y": "a"}`
4. (?) make 'with' optional: `CREATE PREDICTOR pred FROM integration_name  (select * FROM table) ...`

**Comment by ea-rus** [comment]
Do we need support 'create view' for mysql dialect?

**Comment by StpMax** [comment]
@ea-rus 
5. `group by` should be optional

**Comment by ea-rus** [comment]
"group by" is optional now
