### ISSUE TITLE
Planner: constants as identifiers in 'ProjectStep'

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_sql#133]
Let assume we have query:
```
sql = 'select x, 1 from y where z = 1'
```
If parse this query (`parse_sql(sql)`), then we will have two targets: Identifier and Constant
If make plan for this query, then plan will have two steps:
```
plan = plan_query(parse_sql(sql), integrations=['x'], predictor_namespace='mindsdb', predictor_metadata={'x': {}}, default_namespace='mindsdb')
```
Steps:
```
[ApplyPredictorRowStep, ProjectStep]
```
`ProjectStep.columns` will contains two `Identifier`, that is wrong.

**Comment by ea-rus** [comment]
d9eb2791
