### ISSUE TITLE
Delete `CREATE INTEGRATION`

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_sql#141]
Need delete `CREATE INTEGRATION`. Should be only `CREATA DATASOURCE` and `CREATE TABLE`. Also need rename class `CreateIntegration` to `CreateDatasource`

**Comment by ea-rus** [comment]
DROP INTEGRATION also must be removed?

**Comment by StpMax** [comment]
@ea-rus 
1. yes, drop integration is not need anymore
2. CREATE TABLE is alias for CREATE PREDICTOR (for mindsdb dialect)
