### ISSUE TITLE
Slight changes to USING syntax

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_sql#161]
There's 2 requirements I have for the `USING` syntax in order to support the new json-ai.

1. Is it possible to support keys such as `a.b.c`, for example something like:

`USING encoders.rental_price.module = 'NumericEncoder'`, both the key and the value, as before, can be passed to mindsdb as strings. I think this might already be doable

As a followup to that, is it possible to also support something like:
```
USING encoders.'rental price'.module = 'NumericEncoder'`
```
Or in some other way allow ` ` and maybe other special characters as part of the key in `USING`

2. Is it possible to support json for the individual keys in `USING`.

Instead of:

`USING a='{"b": 5, "c": {"d": [1,2,3]}}'`

be able to just have:

`USING a={"b": 5, "c": {"d": [1,2,3]}}`

You needn't make `mindsdb_sql` actually try and parse the json, if it's sent forward as a string to mindsdb that's fine (maybe even better? Since in the future we might want to support dictionaries without json formats as values for the keys in `USING`)

**Comment by ea-rus** [comment]
https://github.com/mindsdb/mindsdb_sql/commit/fa7e2de3d96935dd676c10542411f90739934521

**Comment by ea-rus** [comment]
```
CREATE predictor ...
USING 
    x."part 2".part3=1, 
    y= "a", 
    z=0.7,
    j={'t': [1,2.1,[], {}, False, true, null]},
    q=Filter(a='c', b=2, j={"ar": [1], 'j': {"d": "d"}})
```

is parsed to:

```
CreatePredictor( ...
using={
            'x.part 2.part3': 1,
            'y': "a",
            'z': 0.7,
            'j': {'t': [1,2.1,[], {}, False, True, None]},
            'q': Object(type='Filter', params={
                'a': 'c',
                'b': 1,
                'j': {"ar": [1], 'j': {"d": "d"}}
            })
        },
```

**Comment by ea-rus** [comment]
Do we need to support these variants of "ussing" variables?
```
a=variable,
b=some_module.variable,
c=function_no_params(),
d=function_no_keywords(1,""),
e=module.function_array_as_arg([]),
```
