### ISSUE TITLE
Bug inside USING when parsing lists

### ISSUE THREAD

**Issue by paxcema** [mindsdb/mindsdb_sql#225]
One of Lightwood's top level JsonAI keys is `analysis_blocks`, which is typed as `Optional[List[Module]]`.

Currently, parsing a `CREATE PREDICTOR` query that specifies a value for this key yields a result that Lightwood is not able to interpret.

Example:

```python
from mindsdb_sql import parse_sql

sql = """CREATE PREDICTOR 
  mindsdb.home_rentals_model
FROM example_db
  (SELECT * FROM demo_data.home_rentals)
PREDICT rental_price
USING
analysis_blocks=[{"module": "ShapleyValues"}];
"""

ast = parse_sql(sql, dialect='mindsdb')
```

Inspecting the resulting key, we get:

```python
In[6]: ast.using['analysis_blocks']
Out[6]: [[{'module': 'ShapleyValues'}]]
```

Which is incorrect. The expected value would be `[{'module': 'ShapleyValues'}]`.

**Comment by ea-rus** [comment]
It should have been fixed in: https://github.com/mindsdb/mindsdb_sql/issues/217

**Comment by paxcema** [comment]
Indeed. Apologies, I was testing with a version that didn't include the fix above ^, closing.
