### ISSUE TITLE
[Projects] Changing "get a list of databases" command

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_sql#232]
**Problem:**
user should have a tool for obtaining type of database in mindsdb (is it data connection, of project, or something else we will add leter)

**Current situation:**
at the moment user may get list of databases via:
`show databases;` - returns databases names only
`select * from mindsdb.databases;` - returns also additional info, like type, username and etc
`select * from information_schema.databases;` - same as above

**Proposals:**
1. add to `information_schema.databases` columns determining type ('project' or 'data')
2. extend `show databases` with keyword `full`, like it mysql's `show full tables` command:
https://dev.mysql.com/doc/refman/8.0/en/show-databases.html
https://dev.mysql.com/doc/refman/8.0/en/show-tables.html
With `full` keyword result should contain all additional columns
3. delete 'databases' table from mindsdb 'project'

**Comment by ea-rus** [comment]
I think `show full databases` could be fine

But why not just show database type in `show databases`?

**Comment by StpMax** [comment]
In mysql `show databases` returns only names. As we mimic to mysql, will be good do same

**Comment by ea-rus** [comment]
show full databases - already works
