### ISSUE TITLE
[Project] Changing "get list of predictors" command

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_sql#233]
Problem:
user should have a tool for obtaining list of predictors in particular or all projects

Current situation:
at the moment user may get list of predictors via:
`show predictors [LIKE 'pattern'];` - returns full predictors list with all columns
`select * from mindsdb.predictors` - same as above

Proposals:
1. delete 'predictors' table from mindsdb 'project'. Do not add it to new 'projects'
2. convince users to use `show predictors` as default method to get predictors list
3. extend `show predictors` with `from`:
`show predictors [{FROM | IN} db_name] [LIKE 'pattern' | WHERE expr]`
4. create `information_schema.predictors`

**Comment by ea-rus** [comment]
As I understand list of predictors in project structure will be show with 
`show tables from <projectname>`

**Comment by StpMax** [comment]
`Show tables` returns only names. Also, we can have views, and may be some other types of tables in db

**Comment by ea-rus** [comment]
I think we should stick the same way as dbeaver gets tables and views. It can be: 
Getting butch
`show full tables from project `
or via 2 queries
`show tables from project `
`show views from project `

views - it is views, tables - it is models

**Comment by ea-rus** [comment]
https://github.com/mindsdb/mindsdb/pull/4015
