### ISSUE TITLE
[Project] Changing "get list of predictors versions" command

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_sql#234]
Problem:
user should have a tool for obtaining list of predictors versions

Current situation:
At the moment we have table `mindsdb.predictors_versions`, but will be not very good to copy taht table to each project

Proposals:
1. delete `predictors_versions` from mindsdb 'project'. Do not add it to other projects
2. add to new `information_schema.predictors` infor about all predictors versions. If user need only 'active' predictors, he may filter 'with 'active=True'
3. add new command `show precitors versions [{FROM | IN} db_name] [LIKE 'pattern' | WHERE expr]`

**Comment by ea-rus** [comment]
maybe sql-like way will be more right? We can manipulate verstion with sql commands:
See all versions
`select * from project.model_versions `
Set active selected version
`update project.model_versions where version=3 and model=’modelname’ set active=1 (or true)`
Delete specific version
`delete from project.model_versions where version=3 and model=’modelname’. Exception if version is active `

**Comment by StpMax** [comment]
Im not sure we need 'predictors' ('models') and 'predictors_versions' ('models_versions') in each 'project'. It looks badly and also may bring questions like: why i not see predictors from other db in my 'models' table? or how can i get list of all predictors in all databases?

**Comment by ea-rus** [comment]
As I understand we won't have models table in project and will get list of models using 'show tables from project'

**Comment by paxcema** [comment]
Couldn't `version` be just another `int` column in a global models table? That way we can:

`select * from models where name='name' and active='true'; -- select metadata for active model`

`select * from models where name='name'; -- select all versions for some model name`

And then we could alias the second to a command similar to what @StpMax proposes:

`show [ predictor | model ] versions where name='name'`

**Comment by ea-rus** [comment]
https://github.com/mindsdb/mindsdb/pull/4015
