### ISSUE TITLE
 mindsdb_sql import speed 

### ISSUE THREAD

**Issue by ea-rus** [mindsdb/mindsdb_sql#236]
Import of mindsdb_sql module takes around a second.
It looks like import of Parser module takes a most of that time

**Comment by ea-rus** [comment]
[133f089](https://github.com/mindsdb/mindsdb_sql/commit/133f0897bc6563c15d13185b9030f67304399a46)

**Comment by ea-rus** [comment]
I think the next we can do for speed up is reduce syntax complexity or migrate to another parse library

**Comment by tomhuds** [comment]
Relevant when starting new HF subprocess (needs to import), however now not creating new subprocess for each HF query, so not as relevant.

**Comment by ea-rus** [comment]
Optimization in forked repo makes import 3 times faster https://github.com/ea-rus/sly

**Comment by paxcema** [comment]
Given that sly is retired, perhaps it makes sense to turn this fork into a `mindsdb-sly` package instead?

**Comment by ea-rus** [comment]
Yes, it is a question to discuss, what to do:
- make our own repo and release a new pip module
- make our own repo and not release pip module but install sly from git (or use git submodule) 
- copy sly code to midsdb_sql repo

**Comment by ea-rus** [comment]
Released in #281
