### ISSUE TITLE
Support SET statement

### ISSUE THREAD

**Issue by ea-rus** [mindsdb/mindsdb_sql#251]
Check all SET commands from mysql syntax that not supported yet and enable it in parser

https://dev.mysql.com/doc/refman/8.0/en/set-statement.html

**Comment by drewpotter** [comment]
Hello! I am currently refreshing my Python knowledge and would appreciate giving this issue a go to try and resolve it! I originally reported this issue on Slack 😄 I was trying with the following Rust code:

```rust
use futures::executor::block_on;
use sea_orm::{Database, DbErr};

const DATABASE_URL: &str = "mysql://mindsdb:@localhost:47335";
const DB_NAME: &str = "mindsdb";

async fn run() -> Result<(), DbErr> {
    let db = Database::connect(DATABASE_URL).await?;

    Ok(())
}

pub fn test() {
    println!("MindsDB");
    if let Err(err) = block_on(run()) {
        panic!("{}", err);
    }
}
```

The error I got was:
```bash
SET sql_mode=(SELECT CONCAT(@@sql_mode, ',PIPES_AS_CONCAT,NO_ENGINE_SUBSTITUTION')),time_zone='+00:00',NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
```

I intend to parse those correctly in my fix. Please assign me to this issue 🙏

**Comment by ea-rus** [comment]
Linked issue #196
