### ISSUE TITLE
Allow 'LIMIT' for TS queries

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_sql#26]
At this moment, if query with TS predictor contain 'LIMIT', user will see error:
```
mysql error: Can't provide LIMIT to time series predictor, it will be taken from predictor settings.
```
That is Ok for console clients, but with graphical clients we have problem. Most of them adds to end of query own 'limit'. And there is no way to prevent this behavior. My proposal is: allow 'limit' for ts-queries, but make query to db without it. Add additional planner step to the end with 'limit' applying.

**Comment by btseytlin** [comment]
I see the idea with adding an additional planner step. I think it's a good solution, I will work on it

**Comment by btseytlin** [comment]
Resolved in https://github.com/mindsdb/mindsdb_sql/pull/30
