### ISSUE TITLE
Support escape character in string

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_sql#260]
```
select 'a\ b'
```
String in this query at the moment parsed as is: 'a\ b'
But should be 'a b'

**Comment by StpMax** [comment]
remind :)

**Comment by akshithagunupati** [comment]
Hi @StpMax can I work on this?

**Comment by ea-rus** [comment]
@akshithagunupati, yes, you can try to work on it

**Comment by akshithagunupati** [comment]
@ea-rus Thank you. But is it possible for you to elaborate on the issue please?

**Comment by ea-rus** [comment]
Added support escaping for quotes in #339
```sql
 select 'a \' b'
```

```sql
 select "a \" b"
```
