### ISSUE TITLE
[Bug]: wrong rows count in output

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_sql#264]
### Short description of current behavior

If modify last query from 'Predict Home Rental Prices' tutorial:
```
SELECT *
FROM (select * from example_db.demo_data.home_rentals limit 1) as t 
JOIN mindsdb.home_rentals_model as m limit 100;
```
then 100 rows will be returned

### Expected behavior

Should be returned only 1 row

**Comment by tomhuds** [comment]
Please link PR & add to next release
