### ISSUE TITLE
Add 'default_database' arg to planner

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_sql#27]
Main goal is allow making queries to particular database. For example, we select integration name:
```
use SNOWFLAKE;
```
then make query to table in that database:
```
select * from table;
```
At this moment for that case planner will raise exception `No integration specified for table: table`.
Also that will allow leave integration or 'mindsdb' name:
```
use mindsdb;
select * from integration.table join predictor;
use integration;
select * from table join mindsdb.predictor;
```

**Comment by btseytlin** [comment]
https://github.com/mindsdb/mindsdb_sql/pull/40
