### ISSUE TITLE
Add SQL Support for Knowledge Bases

### ISSUE THREAD

**Issue by tmichaeldb** [mindsdb/mindsdb_sql#287]
See [design doc for more context](https://docs.google.com/document/d/1s5Bi3bwKCTOkHMFn811xuC0OVouxAqZla8AzLCCv1vo/edit#heading=h.imjzg4345aqm)

We should add SQL syntax for:

- Creating a knowledge base
- Deleting a knowledge base
- Updating a knowledge base
- Querying a knowledge base

**Comment by chandrevdw31** [comment]
@tmichaeldb can you link the pr to this issue please

**Comment by chandrevdw31** [comment]
Tested according to https://pastebin.com/FnnUetFX,works accordingly
