### ISSUE TITLE
MindsDB SQL Support for Agents

### ISSUE THREAD

**Issue by tmichaeldb** [mindsdb/mindsdb_sql#295]
See [this design doc](https://docs.google.com/document/d/1QsgqJkhqusp1Ay9YCudoFXuoNzFHoDMMkXhr7AsW9IQ/edit#heading=h.rogj89libxhm) for exact syntax.

We need to support:

- CREATE AGENT
- UPDATE AGENT
- DELETE AGENT

**Comment by chandrevdw31** [comment]
@tmichaeldb can you link the PR please

**Comment by chandrevdw31** [comment]
All syntax parses successfully
