### ISSUE TITLE
Optional `MODEL` token for Retrain/Describe/Finetune

### ISSUE THREAD

**Issue by paxcema** [mindsdb/mindsdb_sql#303]
We may want to support this:

```sql
RETRAIN MODEL model_name
```

In addition to the usual `RETRAIN model_name`.

**Comment by martyna-mindsdb** [comment]
If it is done for `RETRAIN`, let's include these commands as well:

`DESCRIBE [MODEL] ...`
`RETRAIN [MODEL] ...`
`FINETUNE [MODEL] ...`

**Comment by ea-rus** [comment]
In #339 added support of
`RETRAIN [MODEL] ...`
`FINETUNE [MODEL] ...`

This one is already supported
`DESCRIBE [MODEL] ...`
