### ISSUE TITLE
MSSQL parsing does not handle default schema

### ISSUE THREAD

**Issue by QuantumPlumber** [mindsdb/mindsdb_sql#316]
We observe a silent error when database and namespace are used in the FROM component of a CREATE MODEL statement like this:

`CREATE MODEL 
  mindsdb.house_sales_model
FROM mssql_datasource(SELECT * FROM mssql_datasource.dbo.house_sales)
PREDICT price_moving_average
ORDER BY sale_date
GROUP BY bedrooms, building_type
WINDOW 12
HORIZON 3
USING ENGINE = 'statsforecast'; `

Where the mssql_datasource is a connection to the MSSQL MindsDB test server.

One potential customer reports that model training hangs and never returns with the above syntax. 

We have not recreated the hanging training, but we have verified that the above syntax does throw a server error that requests the user to inspect the server error logs (the error is opaque). 

Additionally, we have observed that `public` in postgres throws a good verbose error.

**Comment by ea-rus** [comment]
Just in case: In this syntax query in brackets is the raw query to database and should be without mindsdb datasource name: SELECT * FROM dbo.house_sales
```sql
CREATE MODEL  mindsdb.house_sales_model 
FROM mssql_datasource(SELECT * FROM dbo.house_sales)
PREDICT price_moving_average
ORDER BY sale_date 
GROUP BY bedrooms, building_type
WINDOW 12 
HORIZON 3 
USING ENGINE = 'statsforecast'; 
```

**Comment by tomhuds** [comment]
Sounds like we should catch this syntax error, instead of allowing the model to be stuck on generating indefinitely

**Comment by ea-rus** [comment]
I can't replicate hanging, checked on alpha and cloud: in both cases this query:
```sql
CREATE MODEL  mindsdb.house_sales_model FROM mssql_datasource(SELECT * FROM mssql_datasource.dbo.house_sales) PREDICT price_moving_average ORDER BY sale_date GROUP BY bedrooms, building_type WINDOW 12 HORIZON 3 USING ENGINE = 'statsforecast'; 
```
returns error from mssql database:
![image](https://github.com/mindsdb/mindsdb_sql/assets/8502631/1903b2d9-22a9-4537-98a1-d27fcaf3181a)

**Comment by tomhuds** [comment]
sweet, closing
