### ISSUE TITLE
[Planner] wrong plan if TS model with `= date` filter

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_sql#328]
If have TS `model` and do query:
```sql
select *
from data as t join model as m
            where t.date = '2024-06-26';
```
then plan will be like
 1. [correct] FetchDataframeStep: select distinct groups
 2. [wrong] MapReduceStep: str(steps[1].step.query) =
 ```
 SELECT * FROM data AS t WHERE (((t.date = '2024-06-26')) AND (t.date IS NOT NULL)) AND (t.customerid = '$var[customerid]') ORDER BY t.date DESC
 ```
 3. [wrong] ApplyTimeseriesPredictorStep: output_time_filter = `t.date = '2024-06-26'`
 According to [this doc](https://docs.google.com/spreadsheets/d/1xGsyTcfojNpsZEJ6N0GxzFrS-IwsdoREA_6xFHlw2_w/edit#gid=0), at step №2 should be selected `window` count rows before the date. At step №3 should be appyed filter  `date > '2024-06-26'` (or >=?)

**Comment by akshithagunupati** [comment]
Hi @StpMax can I work on this?
