### ISSUE TITLE
Condition to model in join: exclude predict target

### ISSUE THREAD

**Issue by ea-rus** [mindsdb/mindsdb_sql#347]
Update of: https://github.com/mindsdb/mindsdb_sql/pull/327 (https://github.com/mindsdb/mindsdb/issues/5379)

If column is a model output (like in example below), don't use it as input to model. Keep it as filter
```sql
   SELECT *  FROM yt.comments c
    JOIN yt_sentiment_classifier AS m
    WHERE m.sentiment = 'positive';
```

**Comment by chandrevdw31** [comment]
works


![Image](https://github.com/mindsdb/mindsdb_sql/assets/32901682/c694eeec-00ea-40c6-8d6b-f86b0ba3fc37)

@ea-rus  But the below does not work (following https://github.com/mindsdb/mindsdb/issues/5379)



![Image](https://github.com/mindsdb/mindsdb_sql/assets/32901682/02f8ef6d-aa81-416c-95e8-bb3641d6deea)
