### ISSUE TITLE
Process 'select constant' in planner

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_sql#35]
A lot of clients use 'select constant' to ping server or check something. For example
```
select 1;
select 'test plain returns' as anon_1;
select 'test unicode returns' as anon_1;
select 'keep alive';
etc...
```
At this moment planner raise error when processing such request.
Also, will be good add processing for 'select function'
```
select user();
select database();
select version();
etc...
```

**Comment by btseytlin** [comment]
Resolved in https://github.com/mindsdb/mindsdb_sql/pull/37
