### ISSUE TITLE
Planner is case sensitive

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_sql#36]
At this moment planner raise error if 'integrations' contains name from query in other case. I think this is wrong, because by default mysql is not case sensitive (that could be changed in config). I propose add argument to `plan_query` which will define case sensitive/insensitive behavior. Or just make it all not case-sensitive.

**Comment by btseytlin** [comment]
Resolved in https://github.com/mindsdb/mindsdb_sql/pull/37
