### ISSUE TITLE
Handle columns with dashes in name

### ISSUE THREAD

**Issue by Seanny123** [mindsdb/mindsdb_sql#4]
Currently, as described in https://github.com/mindsdb/dfsql/issues/17, `mindsdb_sql.parse_sql` does not provide a means to escape dashes.

I tried the following, but got different errors for each:
- `"SELECT * FROM df WHERE seq-len > 7"` got converted into `SELECT * FROM df WHERE seq - len > 7`
- `"SELECT * FROM df WHERE 'seq-len' > 7"` made `seq-len` into a string
- `"SELECT * FROM df WHERE seq\-len > 7"` resulted in an error from an invalid character

Is specifying columns with dashes in named supported? If it is, how is it supposed to be specified?

**Comment by btseytlin** [comment]
Answered in https://github.com/mindsdb/dfsql/issues/17#issuecomment-858663585

Also added more tests for this in https://github.com/mindsdb/mindsdb_sql/pull/5
